# Generated by Django 4.2.7 on 2023-12-05 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_listing_listing_current_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='listing_current_price',
        ),
        migrations.AddField(
            model_name='listing',
            name='listing_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='listing_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
