# Generated by Django 4.2.7 on 2023-12-06 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_comments_bids'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='listing_current_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
