# Generated by Django 4.2.7 on 2023-12-06 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_listing_listing_current_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_current_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
