# Generated by Django 4.2.7 on 2023-12-07 15:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_listing_listing_current_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watchlisted_users',
            field=models.ManyToManyField(blank=True, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
